---
title: "How to create faceted runcharts"
author: "John MacKintosh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to create a faceted plot of multiple runcharts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4
)
```



## Faceted plots - 1 column

```{r}
library(runcharter)

p <- runcharter(signals,
                med_rows = 13,
                runlength = 9,
                chart_title = "facet test 1",
                chart_subtitle = " 1 column trellis using facet_wrap", 
                direction = "below",
                faceted = TRUE,
                facet_cols = 1)



```



```{r message=TRUE, warning=TRUE}

library(runcharter)

p <- runcharter(signals,
                med_rows = 13,
                runlength = 9,
                chart_title = "facet test 2",
                chart_subtitle = " 2 column trellis using facet_wrap", 
                direction = "below",
                faceted = TRUE,
                facet_cols = 2)

```








